let Router = require("express").Router;
let router = Router();
let productController = require("../Controllers/Controller");

// API to get all the list of products in the required format
router.get("/products",productController.getListOfProducts);

// API to delete a product based on id 
router.delete("/product/:id", productController.deleteProduct);

// API to search and update the quantity of product. 
router.post("/products/:id/update_quantity/", productController.updateProduct);


// API to create a new product where id is autogenerated.
router.post("/product/create",productController.createProduct);

module.exports=router;

